/* Pseudorandom Number Generator
 * Author: Ethan Z. Seligman
 * 5/3/2021
 */

/* Converts Uint8Array of bytes into UTF-8 string
 * @args: Uint8Array b - bytes to get converted into UTF-8 string
 * @returns: String
 */
function fromBytes(b) {
    return String.fromCharCode.apply(null, b);
}

/* Generates a number by a PRNG based on a seed generated by a TRNG
 * @args: Integer m - max value to get: 0 <= X <= m
 * @returns: Uint8Array
 */
function randomInt(m) {
    var seed = Math.floor(Math.random() * (m + 1)); // initial seed
    var uint8 = new Uint8Array(seed.toString().length) // byte stream
    for (let i = 0; i < uint8.length; i++) {
        let r = Math.floor(Math.random() * (seed.toString().length));
        uint8[i] = seed.toString().charCodeAt(i); // set each byte in stream
    }
    return uint8; // return byte stream
}

for (let i = 0; i < 100; i++) {
    console.log(fromBytes(randomInt(100)));
}
